name: new bounty action

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  newbounty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change README.md
        run: |
          time=$(date +%F -d "${{github.event.issue.updated_at}}")
          echo "- [${{ github.event.issue.title}}](${{github.event.issue.html_url}}) $time" >> README.md
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "bot@rebase.community"
          git add README.md
          git commit -m "submit new bounty (Automated)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: reply
        run: gh issue comment $ISSUE --body "Welcome to submit the bounty information"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
